# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activesupport/all/activesupport.rbi
#
# activesupport-8.1.1

module ActiveSupport
end
class ActiveSupport::TestCase < Minitest::Test
  def __callbacks; end
  def _run_setup_callbacks!(&block); end
  def _run_setup_callbacks(&block); end
  def _run_teardown_callbacks!(&block); end
  def _run_teardown_callbacks; end
  def _setup_callbacks; end
  def _teardown_callbacks; end
  def assert_no_match(matcher, obj, msg = nil); end
  def assert_not_empty(obj, msg = nil); end
  def assert_not_equal(exp, act, msg = nil); end
  def assert_not_in_delta(exp, act, delta = nil, msg = nil); end
  def assert_not_in_epsilon(exp, act, epsilon = nil, msg = nil); end
  def assert_not_includes(collection, obj, msg = nil); end
  def assert_not_instance_of(cls, obj, msg = nil); end
  def assert_not_kind_of(cls, obj, msg = nil); end
  def assert_not_nil(obj, msg = nil); end
  def assert_not_operator(o1, op, o2 = nil, msg = nil); end
  def assert_not_predicate(o1, op, msg = nil); end
  def assert_not_respond_to(obj, meth, msg = nil, include_all: nil); end
  def assert_not_same(exp, act, msg = nil); end
  def file_fixture_path; end
  def file_fixture_path?; end
  def inspect; end
  def method_name; end
  def parallel_worker_id; end
  def self.__callbacks; end
  def self.__callbacks=(value); end
  def self.__class_attr___callbacks; end
  def self.__class_attr___callbacks=(new_value); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.__class_attr_file_fixture_path; end
  def self.__class_attr_file_fixture_path=(new_value); end
  def self._setup_callbacks; end
  def self._setup_callbacks=(value); end
  def self._teardown_callbacks; end
  def self._teardown_callbacks=(value); end
  def self.file_fixture_path; end
  def self.file_fixture_path=(value); end
  def self.file_fixture_path?; end
  def self.parallel_worker_id; end
  def self.parallel_worker_id=(value); end
  def self.parallelize(workers: nil, with: nil, threshold: nil, parallelize_databases: nil); end
  def self.parallelize_before_fork(&block); end
  def self.parallelize_setup(&block); end
  def self.parallelize_teardown(&block); end
  def self.test_order; end
  def self.test_order=(new_order); end
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  extend ActiveSupport::Testing::Declarative
  extend ActiveSupport::Testing::SetupAndTeardown::ClassMethods
  extend Rails::LineFiltering
  include ActiveSupport::Callbacks
  include ActiveSupport::Executor::TestHelper
  include ActiveSupport::Testing::Assertions
  include ActiveSupport::Testing::ConstantStubbing
  include ActiveSupport::Testing::Deprecation
  include ActiveSupport::Testing::ErrorReporterAssertions
  include ActiveSupport::Testing::EventReporterAssertions
  include ActiveSupport::Testing::FileFixtures
  include ActiveSupport::Testing::NotificationAssertions
  include ActiveSupport::Testing::TaggedLogging
  include ActiveSupport::Testing::TimeHelpers
end
