# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actiontext/all/actiontext.rbi
#
# actiontext-8.1.1

module ActionText
end
class ActionText::TrixAttachment
  def attachment_attributes; end
  def attributes; end
  def composed_attributes; end
  def initialize(node); end
  def node; end
  def read_json_attribute(name); end
  def read_json_object_attribute(name); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.from_attributes(attributes); end
  def self.process_attributes(attributes); end
  def self.transform_attribute_keys(attributes); end
  def self.typecast_attribute_values(attributes); end
  def to_html; end
  def to_s; end
end
