# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actionpack/all/actionpack.rbi
#
# actionpack-8.1.1

module ActionController
end
class ActionController::Metal < AbstractController::Base
  include ActionController::Testing::Functional
end
module ActionController::Live
  def original_clean_up_thread_locals(locals, thread); end
  def original_new_controller_thread; end
end
class ActionController::TestRequest < ActionDispatch::TestRequest
  def assign_parameters(routes, controller_path, action, parameters, generated_path, query_string_keys); end
  def content_type=(type); end
  def controller_class; end
  def initialize(env, session, controller_class); end
  def params_parsers; end
  def query_string=(string); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.create(controller_class); end
  def self.default_env; end
  def self.new_session; end
end
class ActionController::LiveTestResponse < ActionController::Live::Response
  def error?; end
  def missing?; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def success?; end
end
class ActionController::TestSession < Rack::Session::Abstract::PersistedSecure::SecureSessionHash
  def destroy; end
  def dig(*keys); end
  def enabled?; end
  def exists?; end
  def fetch(key, *args, &block); end
  def id_was; end
  def initialize(session = nil, id = nil); end
  def keys; end
  def load!; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def values; end
end
class ActionController::TestCase < ActiveSupport::TestCase
  def _controller_class; end
  def _controller_class=(arg0); end
  def _controller_class?; end
  def _run_setup_callbacks(&block); end
  def _run_teardown_callbacks(&block); end
  def self.__class_attr___callbacks; end
  def self.__class_attr___callbacks=(new_value); end
  def self.__class_attr__controller_class; end
  def self.__class_attr__controller_class=(new_value); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self._controller_class; end
  def self._controller_class=(value); end
  def self._controller_class?; end
  def self.executor_around_each_request; end
  def self.executor_around_each_request=(arg0); end
  extend ActionController::TestCase::Behavior::ClassMethods
  extend ActionDispatch::Assertions::RoutingAssertions::ClassMethods
  extend ActiveSupport::Testing::ConstantLookup::ClassMethods
  include ActionController::TemplateAssertions
  include ActionController::TestCase::Behavior
  include ActionDispatch::Assertions
  include ActionDispatch::Assertions::RoutingAssertions
  include ActiveSupport::Testing::ConstantLookup
  include Rails::Controller::Testing::TemplateAssertions
  include Rails::Controller::Testing::TestProcess
end
module ActionController::TestCase::Behavior
  def build_response(klass); end
  def check_required_ivars; end
  def controller_class_name; end
  def delete(action, **args); end
  def document_root_element; end
  def generated_path(generated_extras); end
  def get(action, **args); end
  def head(action, **args); end
  def patch(action, **args); end
  def post(action, **args); end
  def process(action, method: nil, params: nil, session: nil, body: nil, flash: nil, format: nil, xhr: nil, as: nil); end
  def process_controller_response(action, cookies, xhr); end
  def put(action, **args); end
  def query_parameter_names(generated_extras); end
  def request; end
  def response; end
  def scrub_env!(env); end
  def setup_controller_request_and_response; end
  def setup_request(controller_class_name, action, parameters, session, flash, xhr); end
  def wrap_execution(&block); end
  extend ActiveSupport::Concern
  include ActionDispatch::TestProcess
  include ActiveSupport::Testing::ConstantLookup
  include Rails::Dom::Testing::Assertions
end
module ActionController::TestCase::Behavior::ClassMethods
  def controller_class; end
  def controller_class=(new_class); end
  def determine_default_controller_class(name); end
  def tests(controller_class); end
end
