# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actionmailbox/all/actionmailbox.rbi
#
# actionmailbox-8.1.1

module ActionMailbox
end
class ActionMailbox::TestCase < ActiveSupport::TestCase
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  include ActionMailbox::TestHelper
end
