# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activemodel-serializers-xml/all/activemodel-serializers-xml.rbi
#
# activemodel-serializers-xml-1.0.3

module ActiveModel
  extend ActiveModel::Serializers::EagerLoading
end
module ActiveModel::Serializers
  extend ActiveSupport::Autoload
end
module ActiveModel::Serializers::EagerLoading
  def eager_load!; end
end
