# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activerecord/all/activerecord.rbi
#
# activerecord-8.1.1

module ActiveRecord
end
class ActiveRecord::Schema < ActiveRecord::Migration::Current
  def self.[](version); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  extend ActiveRecord::Schema::Definition::ClassMethods
  include ActiveRecord::Schema::Definition
end
module ActiveRecord::Schema::Definition
  def define(info, &block); end
  extend ActiveSupport::Concern
end
module ActiveRecord::Schema::Definition::ClassMethods
  def define(info = nil, &block); end
end
