# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activejob/all/activejob.rbi
#
# activejob-8.1.1

module ActiveJob
end
class ActiveJob::Base
  def __callbacks; end
  def _enqueue_callbacks; end
  def _perform_callbacks; end
  def _run_enqueue_callbacks!(&block); end
  def _run_enqueue_callbacks(&block); end
  def _run_perform_callbacks!(&block); end
  def _run_perform_callbacks; end
  def after_discard_procs; end
  def after_discard_procs=(arg0); end
  def after_discard_procs?; end
  def logger; end
  def logger=(val); end
  def queue_adapter(&); end
  def queue_name_prefix; end
  def queue_name_prefix=(arg0); end
  def queue_name_prefix?; end
  def rescue_handlers; end
  def rescue_handlers=(arg0); end
  def rescue_handlers?; end
  def self.__callbacks; end
  def self.__callbacks=(value); end
  def self.__class_attr___callbacks; end
  def self.__class_attr___callbacks=(new_value); end
  def self.__class_attr__queue_adapter; end
  def self.__class_attr__queue_adapter=(new_value); end
  def self.__class_attr__queue_adapter_name; end
  def self.__class_attr__queue_adapter_name=(new_value); end
  def self.__class_attr_after_discard_procs; end
  def self.__class_attr_after_discard_procs=(new_value); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.__class_attr_enqueue_after_transaction_commit; end
  def self.__class_attr_enqueue_after_transaction_commit=(new_value); end
  def self.__class_attr_log_arguments; end
  def self.__class_attr_log_arguments=(new_value); end
  def self.__class_attr_priority; end
  def self.__class_attr_priority=(new_value); end
  def self.__class_attr_queue_name; end
  def self.__class_attr_queue_name=(new_value); end
  def self.__class_attr_queue_name_delimiter; end
  def self.__class_attr_queue_name_delimiter=(new_value); end
  def self.__class_attr_queue_name_prefix; end
  def self.__class_attr_queue_name_prefix=(new_value); end
  def self.__class_attr_rescue_handlers; end
  def self.__class_attr_rescue_handlers=(new_value); end
  def self.__class_attr_retry_jitter; end
  def self.__class_attr_retry_jitter=(new_value); end
  def self._enqueue_callbacks; end
  def self._enqueue_callbacks=(value); end
  def self._perform_callbacks; end
  def self._perform_callbacks=(value); end
  def self._queue_adapter; end
  def self._queue_adapter=(value); end
  def self._queue_adapter_name; end
  def self._queue_adapter_name=(value); end
  def self.after_discard_procs; end
  def self.after_discard_procs=(value); end
  def self.after_discard_procs?; end
  def self.enqueue_after_transaction_commit; end
  def self.enqueue_after_transaction_commit=(value); end
  def self.log_arguments; end
  def self.log_arguments=(value); end
  def self.log_arguments?; end
  def self.logger; end
  def self.logger=(val); end
  def self.priority; end
  def self.priority=(value); end
  def self.priority?; end
  def self.queue_name; end
  def self.queue_name=(value); end
  def self.queue_name?; end
  def self.queue_name_delimiter; end
  def self.queue_name_delimiter=(value); end
  def self.queue_name_delimiter?; end
  def self.queue_name_prefix; end
  def self.queue_name_prefix=(value); end
  def self.queue_name_prefix?; end
  def self.rescue_handlers; end
  def self.rescue_handlers=(value); end
  def self.rescue_handlers?; end
  def self.retry_jitter; end
  def self.retry_jitter=(value); end
  extend ActiveJob::Callbacks::ClassMethods
  extend ActiveJob::Core::ClassMethods
  extend ActiveJob::Enqueuing::ClassMethods
  extend ActiveJob::Exceptions::ClassMethods
  extend ActiveJob::Execution::ClassMethods
  extend ActiveJob::QueueAdapter::ClassMethods
  extend ActiveJob::QueueName::ClassMethods
  extend ActiveJob::QueuePriority::ClassMethods
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  extend ActiveSupport::Rescuable::ClassMethods
  include ActiveJob::Callbacks
  include ActiveJob::Core
  include ActiveJob::EnqueueAfterTransactionCommit
  include ActiveJob::Enqueuing
  include ActiveJob::Exceptions
  include ActiveJob::Execution
  include ActiveJob::ExecutionState
  include ActiveJob::Instrumentation
  include ActiveJob::Logging
  include ActiveJob::QueueAdapter
  include ActiveJob::QueueName
  include ActiveJob::QueuePriority
  include ActiveRecord::Railties::JobRuntime
  include ActiveSupport::Callbacks
  include ActiveSupport::Rescuable
end
