# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/acts-as-taggable-on/all/acts-as-taggable-on.rbi
#
# acts-as-taggable-on-13.0.0

module ActsAsTaggableOn
end
module ActsAsTaggableOn::TagsHelper
  def tag_cloud(tags, classes); end
end
