# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/addressable/all/addressable.rbi
#
# addressable-2.8.7

module Addressable
end
class Addressable::Template
  def ==(template); end
  def eql?(template); end
  def expand(mapping, processor = nil, normalize_values = nil); end
  def extract(uri, processor = nil); end
  def freeze; end
  def initialize(pattern); end
  def inspect; end
  def join_values(operator, return_value); end
  def keys; end
  def match(uri, processor = nil); end
  def named_captures; end
  def names; end
  def normalize_keys(mapping); end
  def normalize_value(value); end
  def ordered_variable_defaults; end
  def parse_new_template_pattern(pattern, processor = nil); end
  def parse_template_pattern(pattern, processor = nil); end
  def partial_expand(mapping, processor = nil, normalize_values = nil); end
  def pattern; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def source; end
  def to_regexp; end
  def transform_capture(mapping, capture, processor = nil, normalize_values = nil); end
  def transform_partial_capture(mapping, capture, processor = nil, normalize_values = nil); end
  def variable_defaults; end
  def variables; end
end
class Addressable::Template::InvalidTemplateValueError < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Addressable::Template::InvalidTemplateOperatorError < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Addressable::Template::TemplateOperatorAbortedError < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Addressable::Template::MatchData
  def [](key, len = nil); end
  def captures; end
  def initialize(uri, template, mapping); end
  def inspect; end
  def keys; end
  def mapping; end
  def names; end
  def post_match; end
  def pre_match; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def string; end
  def template; end
  def to_a; end
  def to_s; end
  def uri; end
  def values; end
  def values_at(*indexes); end
  def variables; end
end
