# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/airbrussh/all/airbrussh.rbi
#
# airbrussh-1.5.3

module Airbrussh
  def self.configuration(options = nil); end
  def self.configure; end
end
