# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/alchemist/all/alchemist.rbi
#
# alchemist-0.1.8

module Alchemist
  def self.config; end
  def self.library; end
  def self.load_all_categories; end
  def self.load_category(category); end
  def self.measure(value, unit, exponent = nil); end
  def self.measure_prefixed(value, prefix, unit); end
  def self.register(types, names, value); end
  def self.reset!; end
  def self.setup(category = nil); end
end
class Alchemist::IncompatibleTypeError < StandardError
end
class Alchemist::GeospatialArgumentError < StandardError
end
