# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `alchemist` gem.
# Please instead update this file by running `bin/tapioca gem alchemist`.


# source://alchemist//lib/alchemist/conversion_table.rb#3
module Alchemist
  class << self
    # source://alchemist//lib/alchemist.rb#38
    def config; end

    # source://alchemist//lib/alchemist.rb#34
    def library; end

    # source://alchemist//lib/alchemist.rb#53
    def load_all_categories; end

    # source://alchemist//lib/alchemist.rb#57
    def load_category(category); end

    # source://alchemist//lib/alchemist.rb#24
    def measure(value, unit, exponent = T.unsafe(nil)); end

    # source://alchemist//lib/alchemist.rb#28
    def measure_prefixed(value, prefix, unit); end

    # source://alchemist//lib/alchemist.rb#42
    def register(types, names, value); end

    # source://alchemist//lib/alchemist.rb#46
    def reset!; end

    # source://alchemist//lib/alchemist.rb#16
    def setup(category = T.unsafe(nil)); end
  end
end

# source://alchemist//lib/alchemist/compound_measurement.rb#2
class Alchemist::CompoundMeasurement
  include ::Comparable

  # @return [CompoundMeasurement] a new instance of CompoundMeasurement
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#6
  def initialize(numerator); end

  # source://alchemist//lib/alchemist/compound_measurement.rb#20
  def *(value); end

  # source://alchemist//lib/alchemist/compound_measurement.rb#12
  def <=>(other); end

  # Returns the value of attribute denominators.
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#4
  def denominators; end

  # Sets the attribute denominators
  #
  # @param value the value to set the attribute denominators to.
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#4
  def denominators=(_arg0); end

  # Returns the value of attribute numerators.
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#4
  def numerators; end

  # Sets the attribute numerators
  #
  # @param value the value to set the attribute numerators to.
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#4
  def numerators=(_arg0); end

  protected

  # Returns the value of attribute coefficient.
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#79
  def coefficient; end

  private

  # source://alchemist//lib/alchemist/compound_measurement.rb#38
  def compress_units; end

  # source://alchemist//lib/alchemist/compound_measurement.rb#33
  def consolidate; end

  # source://alchemist//lib/alchemist/compound_measurement.rb#70
  def method_missing(method, *attrs, &block); end

  # source://alchemist//lib/alchemist/compound_measurement.rb#46
  def remove_excess_units(numerator, n, denominator, d); end

  # source://alchemist//lib/alchemist/compound_measurement.rb#60
  def set_coefficients; end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/compound_measurement.rb#54
  def should_remove_units?(numerator, denominator); end
end

# source://alchemist//lib/alchemist/configuration.rb#2
class Alchemist::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://alchemist//lib/alchemist/configuration.rb#12
  def initialize; end

  # Returns the value of attribute use_si.
  #
  # source://alchemist//lib/alchemist/configuration.rb#10
  def use_si; end

  # Sets the attribute use_si
  #
  # @param value the value to set the attribute use_si to.
  #
  # source://alchemist//lib/alchemist/configuration.rb#10
  def use_si=(_arg0); end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/configuration.rb#16
  def use_si?; end
end

# source://alchemist//lib/alchemist/configuration.rb#4
Alchemist::Configuration::DATA_DIR = T.let(T.unsafe(nil), String)

# source://alchemist//lib/alchemist/configuration.rb#7
Alchemist::Configuration::DEFAULT_BINARY_PREFIXES_FILE = T.let(T.unsafe(nil), String)

# source://alchemist//lib/alchemist/configuration.rb#6
Alchemist::Configuration::DEFAULT_SI_UNITS_FILE = T.let(T.unsafe(nil), String)

# source://alchemist//lib/alchemist/configuration.rb#5
Alchemist::Configuration::DEFAULT_UNITS_FILE = T.let(T.unsafe(nil), String)

# source://alchemist//lib/alchemist/configuration.rb#8
Alchemist::Configuration::DEFAULT_UNIT_PREFIXES_FILE = T.let(T.unsafe(nil), String)

# source://alchemist//lib/alchemist/conversion_calculator.rb#2
class Alchemist::ConversionCalculator
  # @return [ConversionCalculator] a new instance of ConversionCalculator
  #
  # source://alchemist//lib/alchemist/conversion_calculator.rb#3
  def initialize(from, parsed_unit); end

  # source://alchemist//lib/alchemist/conversion_calculator.rb#8
  def calculate; end

  private

  # source://alchemist//lib/alchemist/conversion_calculator.rb#35
  def base; end

  # source://alchemist//lib/alchemist/conversion_calculator.rb#15
  def exponent; end

  # source://alchemist//lib/alchemist/conversion_calculator.rb#43
  def factor; end

  # Returns the value of attribute from.
  #
  # source://alchemist//lib/alchemist/conversion_calculator.rb#13
  def from; end

  # Returns the value of attribute parsed_unit.
  #
  # source://alchemist//lib/alchemist/conversion_calculator.rb#13
  def parsed_unit; end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/conversion_calculator.rb#31
  def proc_based?; end

  # source://alchemist//lib/alchemist/conversion_calculator.rb#39
  def type; end

  # source://alchemist//lib/alchemist/conversion_calculator.rb#19
  def unit_name; end

  # source://alchemist//lib/alchemist/conversion_calculator.rb#23
  def value; end
end

# source://alchemist//lib/alchemist/conversion_table.rb#4
class Alchemist::ConversionTable
  # source://alchemist//lib/alchemist/conversion_table.rb#6
  def load_all(yaml_file); end

  private

  # source://alchemist//lib/alchemist/conversion_table.rb#51
  def celsius_conversion; end

  # source://alchemist//lib/alchemist/conversion_table.rb#63
  def fahrenheit_conversion; end

  # source://alchemist//lib/alchemist/conversion_table.rb#47
  def from_celsius; end

  # source://alchemist//lib/alchemist/conversion_table.rb#59
  def from_fahrenheit; end

  # source://alchemist//lib/alchemist/conversion_table.rb#14
  def proc_based; end

  # source://alchemist//lib/alchemist/conversion_table.rb#26
  def temperature; end

  # source://alchemist//lib/alchemist/conversion_table.rb#43
  def to_celsius; end

  # source://alchemist//lib/alchemist/conversion_table.rb#55
  def to_fahrenheit; end
end

# source://alchemist//lib/alchemist/objects/planets/earth.rb#2
class Alchemist::Earth
  # @return [Earth] a new instance of Earth
  #
  # source://alchemist//lib/alchemist/objects/planets/earth.rb#5
  def initialize(measurement); end

  # source://alchemist//lib/alchemist/objects/planets/earth.rb#9
  def geospatial; end

  private

  # Returns the value of attribute base.
  #
  # source://alchemist//lib/alchemist/objects/planets/earth.rb#20
  def base; end

  # source://alchemist//lib/alchemist/objects/planets/earth.rb#26
  def geospatial_angle_to_arc; end

  # source://alchemist//lib/alchemist/objects/planets/earth.rb#30
  def geospatial_arc_to_angle; end

  # Returns the value of attribute measurement.
  #
  # source://alchemist//lib/alchemist/objects/planets/earth.rb#20
  def measurement; end

  # source://alchemist//lib/alchemist/objects/planets/earth.rb#22
  def types; end

  class << self
    private

    # source://alchemist//lib/alchemist/objects/planets/earth.rb#2
    def __class_attr_comma_formats; end

    # source://alchemist//lib/alchemist/objects/planets/earth.rb#2
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://alchemist//lib/alchemist/objects/planets/earth.rb#3
Alchemist::Earth::RADIUS = T.let(T.unsafe(nil), Alchemist::Measurement)

# source://alchemist//lib/alchemist.rb#14
class Alchemist::GeospatialArgumentError < ::StandardError; end

# source://alchemist//lib/alchemist.rb#13
class Alchemist::IncompatibleTypeError < ::StandardError; end

# source://alchemist//lib/alchemist/library.rb#2
class Alchemist::Library
  # @return [Library] a new instance of Library
  #
  # source://alchemist//lib/alchemist/library.rb#6
  def initialize; end

  # Returns the value of attribute binary_prefixes.
  #
  # source://alchemist//lib/alchemist/library.rb#4
  def binary_prefixes; end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/library.rb#22
  def binary_unit?(name); end

  # source://alchemist//lib/alchemist/library.rb#30
  def categories; end

  # source://alchemist//lib/alchemist/library.rb#58
  def conversion_base_for(unit_type, unit_name); end

  # Returns the value of attribute conversion_table.
  #
  # source://alchemist//lib/alchemist/library.rb#4
  def conversion_table; end

  # source://alchemist//lib/alchemist/library.rb#54
  def conversions; end

  # source://alchemist//lib/alchemist/library.rb#14
  def exponent_for(name, prefix); end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/library.rb#62
  def has_measurement?(name); end

  # source://alchemist//lib/alchemist/library.rb#40
  def load_all_categories; end

  # source://alchemist//lib/alchemist/library.rb#34
  def load_category(category); end

  # source://alchemist//lib/alchemist/library.rb#75
  def load_conversion_table(filename = T.unsafe(nil)); end

  # source://alchemist//lib/alchemist/library.rb#50
  def measurement_for(unit_name); end

  # source://alchemist//lib/alchemist/library.rb#71
  def operator_actions; end

  # source://alchemist//lib/alchemist/library.rb#83
  def register(type, names, value); end

  # source://alchemist//lib/alchemist/library.rb#66
  def register_operation_conversions(type, other_type, operation, converted_type); end

  # Returns the value of attribute si_units.
  #
  # source://alchemist//lib/alchemist/library.rb#4
  def si_units; end

  # source://alchemist//lib/alchemist/library.rb#46
  def unit_names(category); end

  # Returns the value of attribute unit_prefixes.
  #
  # source://alchemist//lib/alchemist/library.rb#4
  def unit_prefixes; end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/library.rb#26
  def using_binary?; end

  private

  # source://alchemist//lib/alchemist/library.rb#99
  def load_conversions; end
end

# source://alchemist//lib/alchemist/measurement.rb#5
class Alchemist::Measurement
  include ::Comparable

  # @return [Measurement] a new instance of Measurement
  #
  # source://alchemist//lib/alchemist/measurement.rb#10
  def initialize(value, unit_name, exponent = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://alchemist//lib/alchemist/measurement.rb#61
  def *(multiplicand); end

  # source://alchemist//lib/alchemist/measurement.rb#33
  def +(measurement); end

  # source://alchemist//lib/alchemist/measurement.rb#42
  def -(measurement); end

  # source://alchemist//lib/alchemist/measurement.rb#51
  def /(measurement); end

  # source://alchemist//lib/alchemist/measurement.rb#86
  def <=>(other); end

  # source://alchemist//lib/alchemist/measurement.rb#90
  def ==(other); end

  # source://alchemist//lib/alchemist/measurement.rb#69
  def base(unit_type); end

  # source://alchemist//lib/alchemist/measurement.rb#110
  def ceil(*args); end

  # source://alchemist//lib/alchemist/measurement.rb#102
  def coerce(number); end

  # Returns the value of attribute exponent.
  #
  # source://alchemist//lib/alchemist/measurement.rb#8
  def exponent; end

  # source://alchemist//lib/alchemist/measurement.rb#114
  def floor(*args); end

  # source://alchemist//lib/alchemist/measurement.rb#21
  def per; end

  # Returns the value of attribute prefix.
  #
  # source://alchemist//lib/alchemist/measurement.rb#8
  def prefix; end

  # source://alchemist//lib/alchemist/measurement.rb#106
  def round(*args); end

  # source://alchemist//lib/alchemist/measurement.rb#98
  def shared_types(other_unit_name); end

  # source://alchemist//lib/alchemist/measurement.rb#25
  def to(type = T.unsafe(nil)); end

  # source://alchemist//lib/alchemist/measurement.rb#82
  def to_f; end

  # source://alchemist//lib/alchemist/measurement.rb#78
  def to_i; end

  # source://alchemist//lib/alchemist/measurement.rb#74
  def to_s; end

  # source://alchemist//lib/alchemist/measurement.rb#94
  def types; end

  # source://alchemist//lib/alchemist/measurement.rb#17
  def unit_name; end

  # Returns the value of attribute unprefixed_unit_name.
  #
  # source://alchemist//lib/alchemist/measurement.rb#8
  def unprefixed_unit_name; end

  # Returns the value of attribute value.
  #
  # source://alchemist//lib/alchemist/measurement.rb#8
  def value; end

  private

  # source://alchemist//lib/alchemist/measurement.rb#151
  def conversion_base_for(unit_type); end

  # source://alchemist//lib/alchemist/measurement.rb#143
  def convert_to_base(conversion_base); end

  # source://alchemist//lib/alchemist/measurement.rb#171
  def convertor; end

  # source://alchemist//lib/alchemist/measurement.rb#120
  def dividend(measurement); end

  # source://alchemist//lib/alchemist/measurement.rb#137
  def ensure_shared_type!(measurement); end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/measurement.rb#155
  def has_shared_types?(other_unit_name); end

  # @raise [IncompatibleTypeError]
  #
  # source://alchemist//lib/alchemist/measurement.rb#181
  def incompatible_type_error; end

  # source://alchemist//lib/alchemist/measurement.rb#133
  def library; end

  # source://alchemist//lib/alchemist/measurement.rb#175
  def precise_value; end

  # source://alchemist//lib/alchemist/measurement.rb#129
  def remeasure(value); end

  # source://alchemist//lib/alchemist/measurement.rb#159
  def try_raising_dimension(measurement); end
end

# source://alchemist//lib/alchemist/measurement_convertor.rb#5
class Alchemist::MeasurementConvertor
  # @return [MeasurementConvertor] a new instance of MeasurementConvertor
  #
  # source://alchemist//lib/alchemist/measurement_convertor.rb#6
  def initialize(from); end

  # source://alchemist//lib/alchemist/measurement_convertor.rb#10
  def method_missing(method, *args, &block); end

  private

  # source://alchemist//lib/alchemist/measurement_convertor.rb#24
  def convert(parsed_unit); end

  # Returns the value of attribute from.
  #
  # source://alchemist//lib/alchemist/measurement_convertor.rb#17
  def from; end

  # source://alchemist//lib/alchemist/measurement_convertor.rb#19
  def parse_prefix(name); end
end

# source://alchemist//lib/alchemist/module_builder.rb#2
class Alchemist::ModuleBuilder < ::Module
  # @return [ModuleBuilder] a new instance of ModuleBuilder
  #
  # source://alchemist//lib/alchemist/module_builder.rb#3
  def initialize(category); end

  # source://alchemist//lib/alchemist/module_builder.rb#8
  def define_unit_method(names); end

  private

  # source://alchemist//lib/alchemist/module_builder.rb#16
  def define_inspect_method(category); end

  # source://alchemist//lib/alchemist/module_builder.rb#22
  def define_unit_methods(category); end

  # source://alchemist//lib/alchemist/module_builder.rb#36
  def library; end

  # source://alchemist//lib/alchemist/module_builder.rb#44
  def prefixes_for(name); end

  # source://alchemist//lib/alchemist/module_builder.rb#40
  def unit_names(category); end
end

# source://alchemist//lib/alchemist/prefix_parser.rb#2
class Alchemist::PrefixParser
  # @return [PrefixParser] a new instance of PrefixParser
  #
  # source://alchemist//lib/alchemist/prefix_parser.rb#5
  def initialize(unit); end

  # Returns the value of attribute exponent.
  #
  # source://alchemist//lib/alchemist/prefix_parser.rb#3
  def exponent; end

  # source://alchemist//lib/alchemist/prefix_parser.rb#27
  def guess_type(from); end

  # source://alchemist//lib/alchemist/prefix_parser.rb#19
  def prefix_matcher; end

  # @return [Boolean]
  #
  # source://alchemist//lib/alchemist/prefix_parser.rb#23
  def shares_type?(from); end

  # Returns the value of attribute unit_name.
  #
  # source://alchemist//lib/alchemist/prefix_parser.rb#3
  def unit_name; end

  private

  # source://alchemist//lib/alchemist/prefix_parser.rb#42
  def generate_prefix_matcher; end

  # source://alchemist//lib/alchemist/prefix_parser.rb#38
  def library; end

  # source://alchemist//lib/alchemist/prefix_parser.rb#33
  def shared_types(from); end
end
