# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/autoprefixer-rails/all/autoprefixer-rails.rbi
#
# autoprefixer-rails-10.4.21.0

module AutoprefixerRails
  def self.install(assets, params = nil); end
  def self.process(css, opts = nil); end
  def self.processor(params = nil); end
  def self.uninstall(assets); end
end
