# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/barby/all/barby.rbi
#
# barby-0.6.9

module Barby
end
class Barby::PngOutputter < Barby::Outputter
  def background; end
  def background=(c); end
  def foreground; end
  def foreground=(c); end
  def full_height; end
  def full_width; end
  def height; end
  def height=(arg0); end
  def length; end
  def margin; end
  def margin=(arg0); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def to_datastream(*a); end
  def to_image(opts = nil); end
  def to_png(*a); end
  def width; end
  def xdim; end
  def xdim=(arg0); end
  def ydim; end
  def ydim=(arg0); end
end
