# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/builder/all/builder.rbi
#
# builder-3.3.0

module Builder
end
class Builder::XmlEvents < Builder::XmlMarkup
  def _end_tag(sym); end
  def _start_tag(sym, attrs, end_too = nil); end
  def text!(text); end
end
