# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/chunky_png/all/chunky_png.rbi
#
# chunky_png-1.4.0

module ChunkyPNG
end
class ChunkyPNG::Exception < StandardError
end
class ChunkyPNG::NotSupported < ChunkyPNG::Exception
end
class ChunkyPNG::SignatureMismatch < ChunkyPNG::Exception
end
class ChunkyPNG::CRCMismatch < ChunkyPNG::Exception
end
class ChunkyPNG::InvalidUTF8 < ChunkyPNG::Exception
end
class ChunkyPNG::ExpectationFailed < ChunkyPNG::Exception
end
class ChunkyPNG::OutOfBounds < ChunkyPNG::ExpectationFailed
end
class ChunkyPNG::UnitsUnknown < ChunkyPNG::Exception
end
