# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/climate_control/all/climate_control.rbi
#
# climate_control-1.2.0

module ClimateControl
  def _deprecated_env; end
  def copy(overrides); end
  def env(*args, **, &block); end
  def modify(environment_overrides = nil, &block); end
  def unsafe_modify(environment_overrides = nil, &block); end
  extend ClimateControl
  extend Gem::Deprecate
end
