# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `comma` gem.
# Please instead update this file by running `bin/tapioca gem comma`.


# source://comma//lib/comma/relation.rb#3
module ActiveRecord; end

# source://comma//lib/comma/relation.rb#4
class ActiveRecord::Relation
  include ::ActiveModel::ForbiddenAttributesProtection

  # source://comma//lib/comma/relation.rb#5
  def to_comma(style = T.unsafe(nil)); end
end

# source://comma//lib/comma/array.rb#3
class Array
  include ::Enumerable

  # source://comma//lib/comma/array.rb#4
  def to_comma(style = T.unsafe(nil)); end
end

# source://comma//lib/comma.rb#4
CSV_HANDLER = CSV

# source://comma//lib/comma.rb#6
module Comma; end

# source://comma//lib/comma.rb#7
Comma::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# source://comma//lib/comma/data_extractor.rb#6
class Comma::DataExtractor < ::Comma::Extractor
  # source://comma//lib/comma/data_extractor.rb#72
  def __static_column__(_header = T.unsafe(nil), &block); end

  # source://comma//lib/comma/data_extractor.rb#52
  def method_missing(sym, *args, &block); end
end

# source://comma//lib/comma/data_extractor.rb#31
class Comma::DataExtractor::ExtractValueFromAssociationOfInstance < ::Comma::DataExtractor::ExtractValueFromInstance
  # @return [ExtractValueFromAssociationOfInstance] a new instance of ExtractValueFromAssociationOfInstance
  #
  # source://comma//lib/comma/data_extractor.rb#32
  def initialize(instance, association_name); end

  private

  # source://comma//lib/comma/data_extractor.rb#39
  def extraction_object; end

  # source://comma//lib/comma/data_extractor.rb#43
  def null_association; end
end

# source://comma//lib/comma/data_extractor.rb#7
class Comma::DataExtractor::ExtractValueFromInstance
  # @return [ExtractValueFromInstance] a new instance of ExtractValueFromInstance
  #
  # source://comma//lib/comma/data_extractor.rb#8
  def initialize(instance); end

  # source://comma//lib/comma/data_extractor.rb#12
  def extract(sym, &block); end

  private

  # source://comma//lib/comma/data_extractor.rb#22
  def extract_value(method); end

  # source://comma//lib/comma/data_extractor.rb#26
  def extraction_object; end

  # source://comma//lib/comma/data_extractor.rb#18
  def yield_block_with_value(value, &block); end
end

# source://comma//lib/comma/extractor.rb#4
class Comma::Extractor
  # @return [Extractor] a new instance of Extractor
  #
  # source://comma//lib/comma/extractor.rb#5
  def initialize(instance, style, formats); end

  # source://comma//lib/comma/extractor.rb#21
  def __use__(style); end

  # source://comma//lib/comma/extractor.rb#17
  def id(*args, &block); end

  # source://comma//lib/comma/extractor.rb#12
  def results; end

  private

  # source://comma//lib/comma/extractor.rb#28
  def convert_to_data_value(result); end
end

# source://comma//lib/comma/generator.rb#4
class Comma::Generator
  # @return [Generator] a new instance of Generator
  #
  # source://comma//lib/comma/generator.rb#5
  def initialize(instance, style); end

  # source://comma//lib/comma/generator.rb#17
  def run(iterator_method); end

  private

  # source://comma//lib/comma/generator.rb#27
  def append_csv(csv, iterator_method); end
end

# source://comma//lib/comma/header_extractor.rb#11
class Comma::HeaderExtractor < ::Comma::Extractor
  # source://comma//lib/comma/header_extractor.rb#38
  def __static_column__(header = T.unsafe(nil), &_block); end

  # source://comma//lib/comma/header_extractor.rb#19
  def method_missing(sym, *args, &_block); end

  # source://comma//lib/comma/header_extractor.rb#12
  def value_humanizer; end

  # source://comma//lib/comma/header_extractor.rb#12
  def value_humanizer=(_arg0); end

  # source://comma//lib/comma/header_extractor.rb#12
  def value_humanizer?; end

  private

  # source://comma//lib/comma/header_extractor.rb#44
  def get_association_class(model_class, association); end

  class << self
    # source://comma//lib/comma/header_extractor.rb#12
    def value_humanizer; end

    # source://comma//lib/comma/header_extractor.rb#12
    def value_humanizer=(value); end

    # source://comma//lib/comma/header_extractor.rb#12
    def value_humanizer?; end

    private

    # source://comma//lib/comma/header_extractor.rb#12
    def __class_attr_value_humanizer; end

    # source://comma//lib/comma/header_extractor.rb#12
    def __class_attr_value_humanizer=(new_value); end
  end
end

# source://comma//lib/comma/header_extractor.rb#14
Comma::HeaderExtractor::DEFAULT_VALUE_HUMANIZER = T.let(T.unsafe(nil), Proc)

# source://comma//lib/comma/object.rb#6
class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  # source://comma//lib/comma/object.rb#7
  def comma_formats; end

  # source://comma//lib/comma/object.rb#7
  def comma_formats=(_arg0); end

  # source://comma//lib/comma/object.rb#7
  def comma_formats?; end

  # source://comma//lib/comma/object.rb#20
  def to_comma(style = T.unsafe(nil)); end

  # source://comma//lib/comma/object.rb#24
  def to_comma_headers(style = T.unsafe(nil)); end

  private

  # source://comma//lib/comma/object.rb#30
  def extract_with(extractor_class, style = T.unsafe(nil)); end

  # source://comma//lib/comma/object.rb#35
  def raise_unless_style_exists(style); end

  class << self
    # source://comma//lib/comma/object.rb#10
    def comma(style = T.unsafe(nil), &block); end

    # source://comma//lib/comma/object.rb#7
    def comma_formats; end

    # source://comma//lib/comma/object.rb#7
    def comma_formats=(value); end

    # source://comma//lib/comma/object.rb#7
    def comma_formats?; end

    # @private
    #
    # source://comma//lib/comma/object.rb#14
    def inherited(subclass); end

    private

    # source://comma//lib/comma/object.rb#7
    def __class_attr_comma_formats; end

    # source://comma//lib/comma/object.rb#7
    def __class_attr_comma_formats=(new_value); end
  end
end
