# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/config/all/config.rbi
#
# config-5.6.1

module Config
  def self.load_and_set_settings(*sources); end
  def self.load_files(*sources); end
  def self.local_setting_files(config_root, env); end
  def self.reload!; end
  def self.setting_files(config_root, env); end
  def self.setup; end
  extend Anonymous_Config_Configuration_21
  extend Config::Validation::Schema
end
module Anonymous_Config_Configuration_21
  def const_name; end
  def const_name=(value); end
  def dir_name; end
  def dir_name=(value); end
  def env_converter; end
  def env_converter=(value); end
  def env_parse_arrays; end
  def env_parse_arrays=(value); end
  def env_parse_values; end
  def env_parse_values=(value); end
  def env_prefix; end
  def env_prefix=(value); end
  def env_separator; end
  def env_separator=(value); end
  def environment; end
  def environment=(value); end
  def evaluate_erb_in_yaml; end
  def evaluate_erb_in_yaml=(value); end
  def extra_sources; end
  def extra_sources=(value); end
  def fail_on_missing; end
  def fail_on_missing=(value); end
  def file_name; end
  def file_name=(value); end
  def knockout_prefix; end
  def knockout_prefix=(value); end
  def merge_hash_arrays; end
  def merge_hash_arrays=(value); end
  def merge_nil_values; end
  def merge_nil_values=(value); end
  def overwrite_arrays; end
  def overwrite_arrays=(value); end
  def use_env; end
  def use_env=(value); end
  def validation_contract; end
  def validation_contract=(value); end
end
