# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `crossref` gem.
# Please instead update this file by running `bin/tapioca gem crossref`.


# source://crossref//lib/crossref.rb#5
module Crossref; end

# source://crossref//lib/crossref.rb#8
class Crossref::Metadata
  # @return [Metadata] a new instance of Metadata
  #
  # source://crossref//lib/crossref.rb#11
  def initialize(opts = T.unsafe(nil)); end

  # source://crossref//lib/crossref.rb#44
  def authors; end

  # Returns the value of attribute doi.
  #
  # source://crossref//lib/crossref.rb#9
  def doi(doi); end

  # Sets the attribute doi
  #
  # @param value the value to set the attribute doi to.
  #
  # source://crossref//lib/crossref.rb#9
  def doi=(_arg0); end

  # source://crossref//lib/crossref.rb#61
  def journal; end

  # source://crossref//lib/crossref.rb#53
  def published; end

  # source://crossref//lib/crossref.rb#71
  def resource; end

  # @return [Boolean]
  #
  # source://crossref//lib/crossref.rb#30
  def result?; end

  # source://crossref//lib/crossref.rb#39
  def title; end

  # Returns the value of attribute url.
  #
  # source://crossref//lib/crossref.rb#9
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # source://crossref//lib/crossref.rb#9
  def url=(_arg0); end

  # Returns the value of attribute xml.
  #
  # source://crossref//lib/crossref.rb#9
  def xml; end

  # Sets the attribute xml
  #
  # @param value the value to set the attribute xml to.
  #
  # source://crossref//lib/crossref.rb#9
  def xml=(_arg0); end

  # source://crossref//lib/crossref.rb#79
  def xpath_first(q); end

  # source://crossref//lib/crossref.rb#75
  def xpath_ns(q, ns = T.unsafe(nil)); end

  private

  # source://crossref//lib/crossref.rb#91
  def get_xml(url); end

  # source://crossref//lib/crossref.rb#95
  def hashify_nodes(nodes); end

  # source://crossref//lib/crossref.rb#103
  def sanitize_doi(doi); end
end

# source://crossref//lib/crossref.rb#6
Crossref::VERSION = T.let(T.unsafe(nil), String)
