# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/crossref/all/crossref.rbi
#
# crossref-0.0.4

module Crossref
end
class Crossref::Metadata
  def authors; end
  def doi(doi); end
  def doi=(arg0); end
  def get_xml(url); end
  def hashify_nodes(nodes); end
  def initialize(opts = nil); end
  def journal; end
  def published; end
  def resource; end
  def result?; end
  def sanitize_doi(doi); end
  def title; end
  def url; end
  def url=(arg0); end
  def xml; end
  def xml=(arg0); end
  def xpath_first(q); end
  def xpath_ns(q, ns = nil); end
end
