# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/devise/all/devise.rbi
#
# devise-4.9.4

module Devise
end
module Devise::Mailers
end
module Devise::Mailers::Helpers
  def devise_mail(record, action, opts = nil, &block); end
  def devise_mapping; end
  def headers_for(action, opts); end
  def initialize_from_record(record); end
  def mailer_from(mapping); end
  def mailer_reply_to(mapping); end
  def mailer_sender(mapping, sender = nil); end
  def resource; end
  def scope_name; end
  def subject_for(key); end
  def template_paths; end
  extend ActiveSupport::Concern
end
