# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/draper/all/draper.rbi
#
# draper-4.0.6

module Draper
end
module Draper::Decoratable
end
module Draper::Decoratable::CollectionProxy
  def decorate(options = nil); end
end
