# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/drb/all/drb.rbi
#
# drb-2.2.3

module DRb
end
class DRb::DRbUNIXSocket < DRb::DRbTCPSocket
  def accept; end
  def close; end
  def initialize(uri, soc, config = nil, server_mode = nil); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.open(uri, config); end
  def self.open_server(uri, config); end
  def self.parse_uri(uri); end
  def self.temp_server; end
  def self.uri_option(uri, config); end
  def set_sockopt(soc); end
end
