# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erb/all/erb.rbi
#
# erb-6.0.0

class ERB
  def def_class(superklass = nil, methodname = nil); end
  def def_method(mod, methodname, fname = nil); end
  def def_module(methodname = nil); end
  def encoding; end
  def filename; end
  def filename=(arg0); end
  def initialize(str, trim_mode: nil, eoutvar: nil); end
  def lineno; end
  def lineno=(arg0); end
  def location=(arg0); end
  def make_compiler(trim_mode); end
  def new_toplevel(vars = nil); end
  def result(b = nil); end
  def result_with_hash(hash); end
  def run(b = nil); end
  def self.version; end
  def set_eoutvar(compiler, eoutvar = nil); end
  def src; end
end
