# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/exception_notification/all/exception_notification.rbi
#
# exception_notification-4.6.0

module ExceptionNotification
  def self.configure; end
end
