# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/geonames/all/geonames.rbi
#
# geonames-0.3.3

module Geonames
end
class Geonames::Config
  def base_url; end
  def base_url=(arg0); end
  def lang; end
  def lang=(arg0); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def token; end
  def token=(arg0); end
  def username; end
  def username=(arg0); end
end
