# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/globalid/all/globalid.rbi
#
# globalid-1.3.0

class GlobalID
end
class GlobalID::Verifier < ActiveSupport::MessageVerifier
  def decode(data, **); end
  def encode(data, **); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
