# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/gmaps4rails/all/gmaps4rails.rbi
#
# gmaps4rails-2.1.2

module Gmaps4rails
  def self.build_markers(collection, &block); end
end
module Gmaps4rails::Rails
end
