# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `gmaps4rails` gem.
# Please instead update this file by running `bin/tapioca gem gmaps4rails`.


# source://gmaps4rails//lib/gmaps4rails/rails/engine.rb#1
module Gmaps4rails
  class << self
    # source://gmaps4rails//lib/gmaps4rails.rb#13
    def build_markers(collection, &block); end
  end
end

# the to_gmaps4rails method accepts a block to customize:
# - infowindow
# - picture
# - shadow
# - title
# - sidebar
# - json
#
# This works this way:
#   @users = User.all
#   @json  = Gmaps4rails.build_markers @users do |user, marker|
#     marker.lat user.latitude
#     marker.lng user.longitude
#     marker.infowindow render_to_string(:partial => "/users/my_template", :locals => { :object => user}).gsub(/\n/, '').gsub(/"/, '\"')
#     marker.picture({
#                     :url    => "http://www.blankdots.com/img/github-32x32.png",
#                     :width  => "32",
#                     :height => "32"
#                    })
#     marker.title   "i'm the title"
#     marker.json({ :id => user.id })
#   end
#
# source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#24
class Gmaps4rails::MarkersBuilder
  # @return [MarkersBuilder] a new instance of MarkersBuilder
  #
  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#26
  def initialize(collection); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#30
  def call(&block); end

  class << self
    private

    # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#24
    def __class_attr_comma_formats; end

    # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#24
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#36
class Gmaps4rails::MarkersBuilder::MarkerBuilder
  # @return [MarkerBuilder] a new instance of MarkerBuilder
  #
  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#39
  def initialize(object); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#44
  def call(&block); end

  # Returns the value of attribute hash.
  #
  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#38
  def hash; end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#57
  def infowindow(string); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#65
  def json(hash); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#49
  def lat(float); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#53
  def lng(float); end

  # Returns the value of attribute object.
  #
  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#38
  def object; end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#69
  def picture(hash); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#73
  def shadow(hash); end

  # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#61
  def title(string); end

  class << self
    private

    # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#36
    def __class_attr_comma_formats; end

    # source://gmaps4rails//lib/gmaps4rails/markers_builder.rb#36
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://gmaps4rails//lib/gmaps4rails/rails/engine.rb#2
module Gmaps4rails::Rails; end

# source://gmaps4rails//lib/gmaps4rails/rails/engine.rb#3
class Gmaps4rails::Rails::Engine < ::Rails::Engine
  class << self
    private

    # source://gmaps4rails//lib/gmaps4rails/rails/engine.rb#3
    def __class_attr_comma_formats; end

    # source://gmaps4rails//lib/gmaps4rails/rails/engine.rb#3
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://gmaps4rails//lib/gmaps4rails/rails/railtie.rb#3
class Gmaps4rails::Rails::Railtie < ::Rails::Railtie
  class << self
    private

    # source://gmaps4rails//lib/gmaps4rails/rails/railtie.rb#3
    def __class_attr_comma_formats; end

    # source://gmaps4rails//lib/gmaps4rails/rails/railtie.rb#3
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://gmaps4rails//lib/gmaps4rails/version.rb#2
Gmaps4rails::VERSION = T.let(T.unsafe(nil), String)
