# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/http-cookie/all/http-cookie.rbi
#
# http-cookie-1.1.0

class HTTP::CookieJar
  def <<(cookie); end
  def add(cookie); end
  def cleanup(session = nil); end
  def clear; end
  def cookies(url = nil); end
  def delete(cookie); end
  def each(uri = nil, &block); end
  def empty?(url = nil); end
  def get_impl(base, value, *args); end
  def initialize(options = nil); end
  def initialize_copy(other); end
  def load(readable, *options); end
  def parse(set_cookie, origin, options = nil); end
  def save(writable, *options); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.const_missing(name); end
  def store; end
  include Enumerable
end
