# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/http-accept/all/http-accept.rbi
#
# http-accept-1.7.0

module HTTP
end
module HTTP::Accept
end
