# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jbuilder/all/jbuilder.rbi
#
# jbuilder-2.14.1

class Jbuilder::DependencyTracker
  def dependencies; end
  def direct_dependencies; end
  def explicit_dependencies; end
  def indirect_dependencies; end
  def initialize(name, template, view_paths = nil); end
  def name; end
  def resolve_directories(wildcard_dependencies); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.call(name, template, view_paths = nil); end
  def source; end
  def template; end
end
