# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kaminari-core/all/kaminari-core.rbi
#
# kaminari-core-1.2.2

module Kaminari
end
module Kaminari::Helpers
end
module Kaminari::Helpers::UrlHelper
  def next_page_path(scope, options = nil); end
  def next_page_url(scope, options = nil); end
  def path_to_next_page(scope, options = nil); end
  def path_to_next_url(scope, options = nil); end
  def path_to_prev_page(scope, options = nil); end
  def path_to_previous_page(scope, options = nil); end
  def prev_page_path(scope, options = nil); end
  def prev_page_url(scope, options = nil); end
  def previous_page_path(scope, options = nil); end
  def previous_page_url(scope, options = nil); end
  def url_to_next_page(scope, options = nil); end
  def url_to_prev_page(scope, options = nil); end
  def url_to_previous_page(scope, options = nil); end
end
module Kaminari::Helpers::HelperMethods
  def link_to_next_page(scope, name, **options); end
  def link_to_prev_page(scope, name, **options); end
  def link_to_previous_page(scope, name, **options); end
  def page_entries_info(collection, entry_name: nil); end
  def paginate(scope, paginator_class: nil, template: nil, **options); end
  def rel_next_prev_link_tags(scope, options = nil); end
  include Kaminari::Helpers::UrlHelper
end
