# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kgio/all/kgio.rbi
#
# kgio-2.11.4

module Kgio
end
class Kgio::Pipe < IO
  def self.new(*arg0); end
  include Kgio::PipeMethods
end
