# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/libv8-node/all/libv8-node.rbi
#
# libv8-node-16.19.0.1

module Libv8
end
module Libv8::Node
  def self.configure_makefile; end
end
