# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mail/all/mail.rbi
#
# mail-2.9.0

module Mail
end
class Mail::Sendmail
  def deliver!(mail); end
  def destinations_for(envelope); end
  def initialize(values); end
  def popen(command, &block); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def settings; end
  def settings=(arg0); end
end
class Mail::Sendmail::DeliveryError < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
