# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/method_source/all/method_source.rbi
#
# method_source-1.1.0

module MethodSource
  def self.clear_cache; end
  def self.comment_helper(source_location, name = nil); end
  def self.extract_code(source_location); end
  def self.lines_for(file_name, name = nil); end
  def self.source_helper(source_location, name = nil); end
  def self.valid_expression?(str); end
  extend MethodSource::CodeHelpers
end
class MethodSource::SourceNotFoundError < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
module MethodSource::MethodExtensions
  def class_comment; end
  def comment; end
  def module_comment; end
  def self.included(klass); end
  def source; end
end
class Method
  include MethodSource::MethodExtensions
  include MethodSource::SourceLocation::MethodExtensions
end
class UnboundMethod
  include MethodSource::MethodExtensions
  include MethodSource::SourceLocation::UnboundMethodExtensions
end
class Proc
  include MethodSource::MethodExtensions
  include MethodSource::SourceLocation::ProcExtensions
end
