# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/net-ssh/all/net-ssh.rbi
#
# net-ssh-7.3.0

module Net
end
module Net::SSH
  def self._sanitize_options(options); end
  def self._support_deprecated_option_paranoid(options); end
  def self.assign_defaults(options); end
  def self.configuration_for(host, use_ssh_config); end
  def self.start(host, user = nil, options = nil, &block); end
end
