# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/orm_adapter/all/orm_adapter.rbi
#
# orm_adapter-0.5.0

module OrmAdapter
  def self.adapters; end
end
