# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pdf-core/all/pdf-core.rbi
#
# pdf-core-0.10.0

module PDF
end
module PDF::Core
end
module PDF::Core::Errors
end
class PDF::Core::Errors::FailedObjectConversion < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class PDF::Core::Errors::EmptyGraphicStateStack < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class PDF::Core::Errors::InvalidPageLayout < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
