# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pg/all/pg.rbi
#
# pg-1.6.2

module PG
end
module PG::TextDecoder
end
class PG::TextDecoder::Date < PG::SimpleDecoder
  def decode(string, tuple = nil, field = nil); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
