# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/power_assert/all/power_assert.rbi
#
# power_assert-3.0.1

module PowerAssert
  def self.app_caller_locations; end
  def self.app_context?; end
  def self.clear_global_method_cache; end
  def self.internal_file?(file); end
  def self.start(assertion_proc_or_source, assertion_method: nil, source_binding: nil); end
end
module PowerAssert::Empty
end
