# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/prawn/all/prawn.rbi
#
# prawn-2.5.0

module Prawn
  def debug; end
  def debug=(arg0); end
  def self.debug; end
  def self.debug=(arg0); end
  def self.verify_options(accepted, actual); end
  def verify_options(accepted, actual); end
end
