# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/prism/all/prism.rbi
#
# prism-1.6.0

module Prism
  def self.lex_compat(source, **options); end
  def self.lex_ripper(source); end
  def self.load(source, serialized, freeze = nil); end
end
class Prism::CurrentVersionError < ArgumentError
  def initialize(version); end
end
