# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-rails/all/pry-rails.rbi
#
# pry-rails-0.3.11

module PryRails
end
class PryRails::Prompt
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.formatted_env; end
  def self.project_name; end
end
