# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pry-doc` gem.
# Please instead update this file by running `bin/tapioca gem pry-doc`.


# source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#3
class Pry
  extend ::Forwardable
end

# First line is the name of the file
# Following lines are the symbols followed by line number with char 127 as separator.
#
# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#1
module Pry::CInternals; end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#7
class Pry::CInternals::CodeFetcher
  include ::Pry::Helpers::Text

  # @return [CodeFetcher] a new instance of CodeFetcher
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#32
  def initialize(line_number_style: T.unsafe(nil)); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#37
  def fetch_all_definitions(symbol); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#49
  def fetch_first_definition(symbol, index = T.unsafe(nil)); end

  # Returns the value of attribute line_number_style.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#29
  def line_number_style; end

  # Returns the value of attribute symbol_extractor.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#30
  def symbol_extractor; end

  private

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#73
  def start_line_for(line); end

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#69
  def use_line_numbers?; end

  class << self
    # Returns the value of attribute ruby_source_folder.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#11
    def ruby_source_folder; end

    # Sets the attribute ruby_source_folder
    #
    # @param value the value to set the attribute ruby_source_folder to.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#11
    def ruby_source_folder=(_arg0); end

    # Returns the value of attribute ruby_source_installer.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#12
    def ruby_source_installer; end

    # Sets the attribute ruby_source_installer
    #
    # @param value the value to set the attribute ruby_source_installer to.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#12
    def ruby_source_installer=(_arg0); end

    # The Ruby version that corresponds to a downloadable release
    # Note that after Ruby 2.1.0 they exclude the patchlevel from the release name
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#18
    def ruby_version; end

    # Returns a hash that maps C symbols to an array of SourceLocations
    # e.g: symbol_map["VALUE"] #=> [SourceLocation_1, SourceLocation_2]
    # A SourceLocation is defined like this: Struct.new(:file, :line, :symbol_type)
    # e.g file: "foo.c", line: 20, symbol_type: "function"
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#13
    def symbol_map; end

    # Sets the attribute symbol_map
    #
    # @param value the value to set the attribute symbol_map to.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#13
    def symbol_map=(_arg0); end

    private

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#7
    def __class_attr_comma_formats; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/code_fetcher.rb#7
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#11
class Pry::CInternals::ETagParser
  # @return [ETagParser] a new instance of ETagParser
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#14
  def initialize(tags_path, ruby_source_folder); end

  # Returns the value of attribute ruby_source_folder.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#8
  def ruby_source_folder; end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#19
  def symbol_map; end

  # Returns the value of attribute tags_path.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#7
  def tags_path; end

  private

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#54
  def clean_file_name(file_name); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#45
  def file_name_and_content_for(c_file_section); end

  # \f\n  indicates a new C file boundary in the etags file.
  # The first line is the name of the C file, e.g foo.c
  # The successive lines contain information about the symbols for that file.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#35
  def parse_tagfile; end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#50
  def tagfile; end

  class << self
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#10
    def symbol_map_for(tags_path, ruby_source_folder); end

    private

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#11
    def __class_attr_comma_formats; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#11
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#12
class Pry::CInternals::ETagParser::CFile
  # @return [CFile] a new instance of CFile
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#20
  def initialize(file_name: T.unsafe(nil), content: T.unsafe(nil), ruby_source_folder: T.unsafe(nil)); end

  # Returns the value of attribute file_name.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#17
  def file_name; end

  # Sets the attribute file_name
  #
  # @param value the value to set the attribute file_name to.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#17
  def file_name=(_arg0); end

  # Returns the value of attribute ruby_source_folder.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#18
  def ruby_source_folder; end

  # Convert a C file to a map of symbols => SourceLocation that are found in that file
  # e.g
  # { "foo" => [SourceLocation], "bar"  => [SourceLocation] }
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#29
  def symbol_map; end

  private

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#86
  def cleanup_linenumber(line_number); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#81
  def cleanup_symbol(symbol); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#46
  def full_path_for(file_name); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#41
  def source_location_for(symbol, line_number); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#63
  def symbol_type_for(symbol); end

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#55
  def windows?; end

  class << self
    private

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#12
    def __class_attr_comma_formats; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#12
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#15
Pry::CInternals::ETagParser::CFile::ALTERNATIVE_SEPARATOR = T.let(T.unsafe(nil), String)

# Used to separate symbol from line number
#
# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/c_file.rb#14
Pry::CInternals::ETagParser::CFile::SYMBOL_SEPARATOR = T.let(T.unsafe(nil), String)

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
class Pry::CInternals::ETagParser::SourceLocation < ::Struct
  # Returns the value of attribute file
  #
  # @return [Object] the current value of file
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
  def file; end

  # Sets the attribute file
  #
  # @param value [Object] the value to set the attribute file to.
  # @return [Object] the newly set value
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
  def file=(_); end

  # Returns the value of attribute line
  #
  # @return [Object] the current value of line
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
  def line; end

  # Sets the attribute line
  #
  # @param value [Object] the value to set the attribute line to.
  # @return [Object] the newly set value
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
  def line=(_); end

  # Returns the value of attribute symbol_type
  #
  # @return [Object] the current value of symbol_type
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
  def symbol_type; end

  # Sets the attribute symbol_type
  #
  # @param value [Object] the value to set the attribute symbol_type to.
  # @return [Object] the newly set value
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
  def symbol_type=(_); end

  class << self
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def [](*_arg0); end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def inspect; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def keyword_init?; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def members; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def new(*_arg0); end

    private

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def __class_attr_comma_formats; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/etag_parser.rb#5
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#2
class Pry::CInternals::RubySourceInstaller
  # @return [RubySourceInstaller] a new instance of RubySourceInstaller
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#10
  def initialize(ruby_version, ruby_source_folder); end

  # Returns the value of attribute curl_cmd.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#6
  def curl_cmd; end

  # Sets the attribute curl_cmd
  #
  # @param value the value to set the attribute curl_cmd to.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#6
  def curl_cmd=(_arg0); end

  # Returns the value of attribute etag_binary.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#7
  def etag_binary; end

  # Sets the attribute etag_binary
  #
  # @param value the value to set the attribute etag_binary to.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#7
  def etag_binary=(_arg0); end

  # Returns the value of attribute etag_cmd.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#8
  def etag_cmd; end

  # Sets the attribute etag_cmd
  #
  # @param value the value to set the attribute etag_cmd to.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#8
  def etag_cmd=(_arg0); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#17
  def install; end

  # Returns the value of attribute ruby_source_folder.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#4
  def ruby_source_folder; end

  # Returns the value of attribute ruby_version.
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#3
  def ruby_version; end

  private

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#80
  def arch; end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#56
  def ask_for_install; end

  # @param block [&Block] Optional assertion
  # @param message [String] Message to display on error
  # @raise [Pry::CommandError]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#76
  def check_for_error(message, &block); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#66
  def download_ruby; end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#84
  def generate_tagfile; end

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#48
  def linux?; end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#27
  def set_platform_specific_commands; end

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#40
  def windows?; end

  class << self
    private

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#2
    def __class_attr_comma_formats; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/ruby_source_installer.rb#2
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals.rb#4
class Pry::CInternals::ShowSourceWithCInternals < ::Pry::Command::ShowSource
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals.rb#5
  def options(opt); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals.rb#26
  def process; end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals.rb#10
  def show_c_source; end

  private

  # We can number lines with their actual line numbers
  # or starting with 1 (base-one)
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals.rb#42
  def line_number_style; end
end

# source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#2
class Pry::CInternals::SymbolExtractor
  # @return [SymbolExtractor] a new instance of SymbolExtractor
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#8
  def initialize(ruby_source_folder); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#12
  def extract(info); end

  private

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#97
  def balanced?(str); end

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#89
  def complete_function_signature?(str); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#77
  def extract_code(info, offset: T.unsafe(nil), start_line: T.unsafe(nil), direction: T.unsafe(nil), &block); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#55
  def extract_function(info); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#32
  def extract_macro(info); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#50
  def extract_oneliner(info); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#38
  def extract_struct(info); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#44
  def extract_typedef_struct(info); end

  # @return [Boolean]
  #
  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#93
  def function_return_type?(str); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#106
  def source_from_file(file); end

  # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#102
  def token_count(tokens, token); end

  class << self
    # Returns the value of attribute file_cache.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#4
    def file_cache; end

    # Sets the attribute file_cache
    #
    # @param value the value to set the attribute file_cache to.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#4
    def file_cache=(_arg0); end

    private

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#2
    def __class_attr_comma_formats; end

    # source://pry-doc//lib/pry-doc/pry_ext/show_source_with_c_internals/symbol_extractor.rb#2
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#4
module Pry::MethodInfo
  class << self
    # Retrieves aliases of the given method.
    #
    # @param meth [Method, UnboundMethod] The method object
    # @return [Array<UnboundMethod>] the aliases of the given method if they
    #   exist, otherwise an empty array
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#56
    def aliases(meth); end

    # FIXME: this is unnecessarily limited to ext/ and lib/ directories.
    #
    # @return [String] the root directory of a given gem directory
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#73
    def gem_root(dir); end

    # Retrieve the YARD object that contains the method data.
    #
    # @param meth [Method, UnboundMethod] The method object
    # @return [YARD::CodeObjects::MethodObject] the YARD data for the method
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#45
    def info_for(meth); end

    private

    # Caches the file that holds the method.
    #
    # Cannot cache C stdlib and eval methods.
    #
    # @param meth [Method, UnboundMethod] The method object.
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#205
    def cache(meth); end

    # @param meth [Method, UnboundMethod] The method object
    # @return [String, nil] root directory path of gem that method belongs to
    #   or nil if could not be found
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#145
    def find_gem_dir(meth); end

    # Try to recover the gem directory of a gem based on a method object.
    #
    # @param meth [Method, UnboundMethod] The method object
    # @return [String, nil] the located gem directory
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#188
    def gem_dir_from_method(meth); end

    # Try to guess what the gem name will be based on the name of the module.
    #
    # @param name [String] The name of the module
    # @return [Enumerator] the enumerator which enumerates on possible names
    #   we try to guess
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#171
    def guess_gem_name(name); end

    # Checks whether `meth` is a class method.
    #
    # @param meth [Method, UnboundMethod] The method to check
    # @return [Boolean] true if singleton, otherwise false
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#101
    def is_singleton?(meth); end

    # @return [Object] the host of the method (receiver or owner)
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#137
    def method_host(meth); end

    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#226
    def namespace_name(host); end

    # Attempts to find the C source files if method belongs to a gem and use
    # YARD to parse and cache the source files for display.
    #
    # @param meth [Method, UnboundMethod] The method object
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#125
    def parse_and_cache_if_gem_cext(meth); end

    # Convert a method object into the `Class#method` string notation.
    #
    # @note This mess is needed to support all the modern Rubies. Somebody has
    #   to figure out a better way to distinguish between class methods and
    #   instance methods.
    # @param meth [Method, UnboundMethod]
    # @return [String] the method in string receiver notation
    #
    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#88
    def receiver_notation_for(meth); end

    # source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#105
    def registry_lookup(meth); end
  end
end

# @return [Regexp] a pattern that matches `method_instance.inspect`
#
# source://pry-doc//lib/pry-doc/pry_ext/method_info.rb#6
Pry::MethodInfo::METHOD_INSPECT_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://pry-doc//lib/pry-doc.rb#1
module PryDoc
  class << self
    # source://pry-doc//lib/pry-doc.rb#2
    def load_yardoc(version); end

    # source://pry-doc//lib/pry-doc.rb#14
    def root; end
  end
end

# source://pry-doc//lib/pry-doc/version.rb#2
PryDoc::VERSION = T.let(T.unsafe(nil), String)
