# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-stack_explorer/all/pry-stack_explorer.rbi
#
# pry-stack_explorer-0.6.1

module PryStackExplorer
  def self.bindings_equal?(b1, b2); end
  def self.clear_frame_managers(_pry_); end
  def self.create_and_push_frame_manager(bindings, _pry_, options = nil); end
  def self.delete_frame_managers(_pry_); end
  def self.frame_hash; end
  def self.frame_manager(_pry_); end
  def self.frame_managers(_pry_); end
  def self.pop_frame_manager(_pry_); end
  def self.pop_helper(popped_fm, _pry_); end
  def self.push_helper(fm, options = nil); end
end
