# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-byebug/all/pry-byebug.rbi
#
# pry-byebug-3.10.1

module PryByebug
end
class PryByebug::ExitAllCommand < Pry::Command::ExitAll
  def process; end
end
