# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/puma/all/puma.rbi
#
# puma-6.6.1

module Puma
end
class Puma::Launcher
  def binder; end
  def close_binder_listeners; end
  def clustered?; end
  def config; end
  def connected_ports; end
  def delete_pidfile; end
  def do_forceful_stop; end
  def do_graceful_stop; end
  def do_restart(previous_env); end
  def do_run_finished(previous_env); end
  def environment; end
  def events; end
  def generate_restart_data; end
  def get_env; end
  def halt; end
  def initialize(conf, launcher_args = nil); end
  def log(str); end
  def log_config; end
  def log_writer; end
  def options; end
  def phased_restart; end
  def prune_bundler!; end
  def prune_bundler?; end
  def refork; end
  def reload_worker_directory; end
  def restart!; end
  def restart; end
  def restart_args; end
  def restart_dir; end
  def run; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def set_process_title; end
  def set_rack_environment; end
  def setup_signals; end
  def stats; end
  def stop; end
  def thread_status; end
  def title; end
  def unsupported(str); end
  def write_pid; end
  def write_state; end
end
