# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-session/all/rack-session.rbi
#
# rack-session-2.1.1

module Rack
end
module Rack::Session
end
class Rack::Session::Cookie < Rack::Session::Abstract::PersistedSecure
  def coder; end
  def delete_session(req, session_id, options); end
  def encode_session_data(session); end
  def encryptors; end
  def extract_session_id(request); end
  def find_session(req, sid); end
  def initialize(app, options = nil); end
  def legacy_digest_match?(data, digest); end
  def legacy_generate_hmac(data); end
  def persistent_session_id!(data, sid = nil); end
  def secure?(options); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def unpacked_cookie_data(request); end
  def write_session(req, session_id, session, options); end
end
class Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(str); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Rack::Session::Cookie::Base64::Marshal < Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(str); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Rack::Session::Cookie::Base64::JSON < Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(obj); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Rack::Session::Cookie::Base64::ZipJSON < Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(obj); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Rack::Session::Cookie::Identity
  def decode(str); end
  def encode(str); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Rack::Session::Cookie::Marshal
  def decode(str); end
  def encode(str); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
class Rack::Session::Cookie::SessionId < Anonymous_Delegator_30
  def cookie_value; end
  def initialize(session_id, cookie_value); end
end
