# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails-controller-testing/all/rails-controller-testing.rbi
#
# rails-controller-testing-1.0.5

module Rails
end
module Rails::Controller
end
module Rails::Controller::Testing
end
