# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rak` gem.
# Please instead update this file by running `bin/tapioca gem rak`.


# source://rak//lib/rak.rb#2
class Rak
  class << self
    private

    # source://rak//lib/rak.rb#2
    def __class_attr_comma_formats; end

    # source://rak//lib/rak.rb#2
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://rak//lib/rak.rb#3
Rak::VERSION = T.let(T.unsafe(nil), String)
