# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ransack/all/ransack.rbi
#
# ransack-4.3.0

module Ransack
end
module Ransack::Helpers
end
module Ransack::Helpers::FormHelper
  def extract_search_and_routing_proxy(search); end
  def html_option_for(option, search); end
  def options_for(record); end
  def parse_record(object); end
  def search_form_for(record, options = nil, &proc); end
  def sort_link(search_object, attribute, *args, &block); end
  def sort_url(search_object, attribute, *args); end
  def url(routing_proxy, options_for_url); end
end
class Ransack::Helpers::FormHelper::SortLink
  def default_arrow; end
  def default_sort_order(attr_name); end
  def detect_previous_sort_direction_and_invert_it(attr_name); end
  def direction_text(dir); end
  def down_arrow; end
  def existing_sort_direction(f = nil); end
  def extract_label_and_mutate_args!(args); end
  def extract_options_and_mutate_args!(args); end
  def extract_sort_fields_and_mutate_args!(args); end
  def html_options(args); end
  def initialize(search, attribute, args, params); end
  def name; end
  def no_sort_direction_specified?(dir = nil); end
  def order_indicator; end
  def parameters_hash(params); end
  def parse_sort(field); end
  def recursive_sort_params_build(fields); end
  def search_and_sort_params; end
  def search_params; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def sort_params; end
  def up_arrow; end
  def url_options; end
end
