# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/responders/all/responders.rbi
#
# responders-3.2.0

module ActionController
end
module ActionController::RespondWith
  def collect_mimes_from_class_level; end
  def respond_with(*resources, &block); end
  def verify_request_format!; end
  def verify_requested_format!; end
  extend ActiveSupport::Concern
end
module ActionController::RespondWith::ClassMethods
  def clear_respond_to; end
  def respond_to(*mimes); end
end
