# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rest-client/all/rest-client.rbi
#
# rest-client-2.1.0

module RestClient
  def self.add_before_execution_proc(&proc); end
  def self.before_execution_procs; end
  def self.create_log(param); end
  def self.delete(url, headers = nil, &block); end
  def self.get(url, headers = nil, &block); end
  def self.head(url, headers = nil, &block); end
  def self.log; end
  def self.log=(log); end
  def self.options(url, headers = nil, &block); end
  def self.patch(url, payload, headers = nil, &block); end
  def self.post(url, payload, headers = nil, &block); end
  def self.proxy; end
  def self.proxy=(value); end
  def self.proxy_set?; end
  def self.put(url, payload, headers = nil, &block); end
  def self.reset_before_execution_procs; end
end
