# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rexml/all/rexml.rbi
#
# rexml-3.4.4

module REXML
end
module REXML::StreamListener
  def attlistdecl(element_name, attributes, raw_content); end
  def cdata(content); end
  def comment(comment); end
  def doctype(name, pub_sys, long_name, uri); end
  def doctype_end; end
  def elementdecl(content); end
  def entity(content); end
  def entitydecl(content); end
  def instruction(name, instruction); end
  def notationdecl(content); end
  def tag_end(name); end
  def tag_start(name, attrs); end
  def text(text); end
  def xmldecl(version, encoding, standalone); end
end
