# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-mocks/all/rspec-mocks.rbi
#
# rspec-mocks-3.13.7

module RSpec
end
module RSpec::Mocks
end
module RSpec::Mocks::Matchers
end
class RSpec::Mocks::Matchers::ReceiveMessages
  def any_instance_of(subject); end
  def description; end
  def does_not_match?(_subject); end
  def each_message_on(host); end
  def initialize(message_return_value_hash); end
  def matcher_name; end
  def matches?(subject); end
  def proxy_on(subject); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def setup_allowance(subject); end
  def setup_any_instance_allowance(subject); end
  def setup_any_instance_expectation(subject); end
  def setup_expectation(subject); end
  def setup_negative_expectation(_subject); end
  def warn_about_block; end
  include RSpec::Mocks::Matchers::Matcher
end
