# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-expectations/all/rspec-expectations.rbi
#
# rspec-expectations-3.13.5

module RSpec
end
module RSpec::Matchers
end
module RSpec::Matchers::BuiltIn
end
class RSpec::Matchers::BuiltIn::YieldProbe
  def assert_used!; end
  def assert_valid_expect_block!; end
  def has_block?; end
  def initialize(block, &callback); end
  def num_yields; end
  def num_yields=(arg0); end
  def probe; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.probe(block, &callback); end
  def single_yield_args; end
  def to_proc; end
  def yielded_args; end
  def yielded_args=(arg0); end
  def yielded_once?(matcher_name); end
end
class RSpec::Matchers::BuiltIn::YieldControl < RSpec::Matchers::BuiltIn::BaseMatcher
  def does_not_match?(block); end
  def failure_message; end
  def failure_message_when_negated; end
  def failure_reason; end
  def matches?(block); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def supports_block_expectations?; end
  def supports_value_expectations?; end
  include RSpec::Matchers::BuiltIn::CountExpectation
end
class RSpec::Matchers::BuiltIn::YieldWithNoArgs < RSpec::Matchers::BuiltIn::BaseMatcher
  def does_not_match?(block); end
  def failure_message; end
  def failure_message_when_negated; end
  def matches?(block); end
  def negative_failure_reason; end
  def positive_failure_reason; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def supports_block_expectations?; end
  def supports_value_expectations?; end
end
class RSpec::Matchers::BuiltIn::YieldWithArgs < RSpec::Matchers::BuiltIn::BaseMatcher
  def all_args_match?; end
  def args_currently_match?; end
  def description; end
  def does_not_match?(block); end
  def expected_arg_description; end
  def failure_message; end
  def failure_message_when_negated; end
  def initialize(*args); end
  def matches?(block); end
  def negative_failure_reason; end
  def positive_failure_reason; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def supports_block_expectations?; end
  def supports_value_expectations?; end
end
class RSpec::Matchers::BuiltIn::YieldSuccessiveArgs < RSpec::Matchers::BuiltIn::BaseMatcher
  def description; end
  def does_not_match?(block); end
  def expected_arg_description; end
  def failure_message; end
  def failure_message_when_negated; end
  def initialize(*args); end
  def matches?(block); end
  def negative_failure_reason; end
  def positive_failure_reason; end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def supports_block_expectations?; end
  def supports_value_expectations?; end
end
