# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec_junit_formatter/all/rspec_junit_formatter.rbi
#
# rspec_junit_formatter-0.6.0

class RSpecJUnitFormatter < RSpec::Core::Formatters::BaseFormatter
  def escape(text); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def strip_diff_colors(string); end
  def xml_dump; end
  def xml_dump_example(example); end
  def xml_dump_examples; end
  def xml_dump_failed(example); end
  def xml_dump_output(example); end
  def xml_dump_pending(example); end
end
