# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sassc-rails/all/sassc-rails.rbi
#
# sassc-rails-2.1.2

module SassC::Rails
end
class SassC::Rails::Railtie < Rails::Railtie
end
