# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-rcov` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-rcov`.


# source://simplecov-rcov//lib/simplecov-rcov/version.rb#1
module SimpleCov; end

# source://simplecov-rcov//lib/simplecov-rcov/version.rb#2
module SimpleCov::Formatter; end

# source://simplecov-rcov//lib/simplecov-rcov/version.rb#3
class SimpleCov::Formatter::RcovFormatter
  # source://simplecov-rcov//lib/simplecov-rcov.rb#16
  def format(result); end

  private

  # source://simplecov-rcov//lib/simplecov-rcov.rb#96
  def asset_output_path; end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#107
  def assets_path(name); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#111
  def code_coverage_html(code_coverage_percentage, is_total = T.unsafe(nil)); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#79
  def coverage(file_list); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#86
  def coverage_code(file_list); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#124
  def coverage_threshold_classes(percentage); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#137
  def file_filter_classes(file_path); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#141
  def line_css_for(coverage); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#60
  def lines(file_list); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#65
  def lines_covered(file_list); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#70
  def lines_missed(file_list); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#75
  def lines_of_code(file_list); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#103
  def project_name; end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#133
  def relative_filename(path); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#129
  def shortened_filename(file); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#56
  def template(name); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#119
  def total_coverage_for_report(file); end

  # source://simplecov-rcov//lib/simplecov-rcov.rb#48
  def write_file(template, output_filename, binding); end

  class << self
    # source://simplecov-rcov//lib/simplecov-rcov.rb#92
    def output_path; end

    private

    # source://simplecov-rcov//lib/simplecov-rcov/version.rb#3
    def __class_attr_comma_formats; end

    # source://simplecov-rcov//lib/simplecov-rcov/version.rb#3
    def __class_attr_comma_formats=(new_value); end
  end
end

# source://simplecov-rcov//lib/simplecov-rcov.rb#14
SimpleCov::Formatter::RcovFormatter::UPSTREAM_URL = T.let(T.unsafe(nil), String)

# source://simplecov-rcov//lib/simplecov-rcov/version.rb#4
SimpleCov::Formatter::RcovFormatter::VERSION = T.let(T.unsafe(nil), String)
