# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sprockets/all/sprockets.rbi
#
# sprockets-4.2.2

module Sprockets
end
class Sprockets::Cache
end
class Sprockets::Cache::FileStore
  def clear(options = nil); end
  def compute_size(caches); end
  def find_caches; end
  def gc!; end
  def get(key); end
  def initialize(root, max_size = nil, logger = nil); end
  def inspect; end
  def safe_open(path, &block); end
  def safe_stat(fn); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.default_logger; end
  def set(key, value); end
  def size; end
end
