# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sshkit/all/sshkit.rbi
#
# sshkit-1.24.0

module SSHKit
  def self.config; end
  def self.config=(arg0); end
  def self.configure; end
  def self.reset_configuration!; end
end
class SSHKit::StandardError < StandardError
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
end
module SSHKit::Redaction
end
