# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/terser/all/terser.rbi
#
# terser-1.2.6

class Terser
end
class Terser::Compressor
  def cache_key; end
  def call(input); end
  def initialize(options = nil); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def self.cache_key; end
  def self.call(input); end
  def self.instance; end
end
