# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/thor/all/thor.rbi
#
# thor-1.4.0

class Thor
end
module Thor::Actions
  def _cleanup_options_and_set(options, key); end
  def _shared_configuration; end
  def action(instance); end
  def apply(path, config = nil); end
  def behavior; end
  def behavior=(arg0); end
  def destination_root; end
  def destination_root=(root); end
  def find_in_source_paths(file); end
  def in_root; end
  def initialize(args = nil, options = nil, config = nil); end
  def inside(dir = nil, config = nil, &block); end
  def relative_to_original_destination_root(path, remove_dot = nil); end
  def run(command, config = nil); end
  def run_ruby_script(command, config = nil); end
  def self.included(base); end
  def source_paths; end
  def thor(command, *args); end
end
module Thor::Actions::ClassMethods
  def add_runtime_options!; end
  def source_paths; end
  def source_paths_for_search; end
  def source_root(path = nil); end
end
