# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ttfunk/all/ttfunk.rbi
#
# ttfunk-1.8.0

module TTFunk
end
class TTFunk::SubsetCollection
  def [](subset); end
  def encode(characters); end
  def initialize(original); end
  def self.__class_attr_comma_formats; end
  def self.__class_attr_comma_formats=(new_value); end
  def use(characters); end
end
