# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unicorn/all/unicorn.rbi
#
# unicorn-6.1.0

module Unicorn
  def self.builder(ru, op); end
  def self.listener_names; end
  def self.log_error(logger, prefix, exc); end
  def self.pipe; end
end
class Unicorn::ClientShutdown < EOFError
end
