# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SpotDecorator`.
# Please instead update this file by running `bin/tapioca dsl SpotDecorator`.


class SpotDecorator
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
